services:
  sharelatex:
    image: sharelatex/sharelatex
    depends_on:
      mongo:
        condition: service_healthy
      redis:
        condition: service_started
    links:
      - mongo
      - redis
    networks:
      - default
      - proxy
    volumes:
      # - /mnt/storage/overleaf:/var/lib/overleaf
      - ./overleaf:/var/lib/overleaf
    restart: unless-stopped
    environment:
      VIRTUAL_HOST: overleaf.jeschek.eu
      LETSENCRYPT_HOST: overleaf.jeschek.eu
      OVERLEAF_APP_NAME: Overleaf Community Edition
      OVERLEAF_MONGO_URL: mongodb://mongo/overleaf
      OVERLEAF_REDIS_HOST: redis
      REDIS_HOST: redis
      ENABLED_LINKED_FILE_TYPES: 'url,project_file'
      ENABLE_CONVERSIONS: 'true' # thumbnail conversions using imagemagick
      EMAIL_CONFIRMATION_DISABLED: 'true'
      TEXMFVAR: /var/lib/overleaf/tmp/texmf-var # temporary fix for LuaLaTex compiles,  see https://github.com/overleaf/overleaf/issues/695
      OVERLEAF_SITE_URL: https://overleaf.jeschek.eu
      OVERLEAF_NAV_TITLE: Joshs Overleaf
      OVERLEAF_HEADER_IMAGE_URL: https://cloud.jeschek.eu/s/2nddajPgCBBXTT9/download/overleaf.png
      OVERLEAF_ADMIN_EMAIL: dev@jeschek.eu
      OVERLEAF_EMAIL_SMTP_HOST: smtp.purelymail.com
      OVERLEAF_EMAIL_SMTP_PORT: 465
      OVERLEAF_EMAIL_SMTP_SECURE: true
      OVERLEAF_EMAIL_SMTP_USER: overleaf@jeschek.eu
      OVERLEAF_EMAIL_SMTP_PASS: ${SMTP_PASSWORD}

  mongo:
    restart: always
    image: mongo:6.0
    container_name: mongo
    command: '--replSet overleaf'
    expose:
      - 27017
    volumes:
      - ./mongo:/data/db
      - ./bin/shared/mongodb-init-replica-set.js:/docker-entrypoint-initdb.d/mongodb-init-replica-set.js
    environment:
      MONGO_INITDB_DATABASE: sharelatex
    extra_hosts:
      # Required when using the automatic database setup for initializing the replica set.
      # This override is not needed when running the setup after starting up mongo.
      - mongo:127.0.0.1
    healthcheck:
      test: echo 'db.stats().ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5

  redis:
    restart: always
    image: redis:6.2
    container_name: redis
    expose:
      - 6379
    volumes:
      - ./redis:/data

  # ldap:
  #  restart: always
  #  image: rroemhild/test-openldap
  #  container_name: ldap
  #  expose:
  #    - 389

networks:
  proxy:
    external: true
